### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/farm-budgets-data#1]
@qjhart The current file structure (a quick guess) puts the budget name for each file... this can make updating a budgets name a pain.  Would a better structure be:

```
[budget name]
  \- [State]
    \- costs.csv
    \- zipcode (optional)
    \- county (optional)
    \- crops
      \- [crop name].csv
```

This would make copying a budget easier.  Though searching for, say, which budgets have Alfalfa in Sacramento County, CA a pain.

**Comment by qjhart** [comment]
I'm not sure about this either.  Currently, I'm thinking we need to more completely separate costs, and budgets, and I think most of the time we will have costs covering the entire region, so I'm thiking:

```
\Costs
 \- fuel.csv   (Header = fipscode | year | on-road | off-road  )
 \- labor.csv (header = fipscode | type [enum driver|machine|laboror|etc] | year | cost )
 \- supplies (header = fipscode | type | year | unit | cost ) 
```

or maybe 

```
\- supplies
 \-- Pesticides.csv ()
  \-- fertilizer () 
```

Then for budgets, I guess in the end we want 

```
\Budget 
  \- blueberries.csv (fips |  item | amount | unit ) 
```

where items can be found in the costs tables. and amounts can change from fipscode to fipscode

This doesn't have authorities in there yet? 

maybe: 

```
budget
- [authority name]
-- blueberries.csv 
```

**Comment by qjhart** [comment]
@ncparker @jrmerz This is still not finalized, and I am changing file locations willy-nilly still.  Soon, I will start getting your approval beforehand, but not yet. 

Current strategy is more simple:
data/[authority]
Then in authority, you divide however you want, but prices, end in _price.  Maybe that's not the best idea.
