### ISSUE TITLE
Need to come up with labor estimates for all the worker types

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#10]
Judy sez that some of her Ag budgets only have $ for labor, not hours or type of labor.

**Comment by qjhart** [comment]
@blyeo Yo see from this note, that you and @judyhanna need to make sure the production materials is broken down by labor type and hours.

**Comment by blyeo** [comment]
Will follow-up with Judy on this tomorrow (Wed). Thank you.

**Comment by judyhanna** [comment]
@ncparker Could you send me the BLS data?

**Comment by ncparker** [comment]
@judyhanna Here is what I have.  I only have one time step for the data.
The more historical data may be available using an API at the BLS website.

**Comment by blyeo** [comment]
Hi Nathan, Is there any chance you can send the files from the BLS to me
and Judy today? We'd like to work on figuring out data for "labor in
dollars per acre" for the SWAP analysis. We couldn't find it on github if
you have already posted it there so we were wondering if you could please
just send the files to us.

Thank you,
Boon Ling

**Comment by qjhart** [comment]
@blyeo and @judyhanna , I guess have solved this.
