### ISSUE TITLE
Stop Gap Labor costs by getting B Labor Statistics.

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#11]
Get an estimate of the BLS statewide Labor costs.

**Comment by ncparker** [comment]
Looks like I can pull data at the spatial resolution of the county or groups of counties from the BLS.  I will try to pull a time series for ag. machine operators for the region and see what the data looks like.

**Comment by ncparker** [comment]
The BLS data is proving difficult in time series, It is possible I'm an idiot and missing the way to get at the data.  I have pulled the latest data for farm equipment operators (452091) and farm laborers (452092) for the MSAs in the region and state level.  Still need to match the BLS MSA areas to counties. and possibly use State averages where there is no coverage.

**Comment by qjhart** [comment]
@ncparker and @blyeo decided that a method to calculate data for labor is to add an additional statewide labor for minimum wages.  Then use existing ratios between machine and non-machine in order to gap fill these values at the State Level.

**Comment by qjhart** [comment]
@ncparker is it worth sending the API to @jrmerz to see about investigating the BLS API?

**Comment by ncparker** [comment]
@jrmerz here's a link to the BLS developer site http://www.bls.gov/developers/ I am trying to get historical data for hourly mean wage for the occupations Agricultural Equipment Operators (SOC code 452091)  and Farmworkers and Laborers, Crop, Nursery, and Greenhouse (SOC code 452092) by MSA.  This link is a table for all occupations in CA basically the data we are looking for on an MSA basis for the codes above. http://www.bls.gov/oes/current/oes_ca.htm  

If there is an obvious path to getting the API to do what we want then go for it  other wise let me know to muddle along.

**Comment by qjhart** [comment]
@jrmerz / @ncparker  Nathan will need to help Justin with the code to use.  Look here, http://www.bls.gov/help/hlpforma.htm for the format of this which is confusing to me.   Here's an example, but I don't know why we can't get a history for the OES data

``` bash
curl -i -X POST -H 'Content-Type: application/json' -d '{"seriesid": ["EEU31352303","OEUS060000000000045209103"],"startyear":2010,"endyear":2014}' http://api.bls.gov/publicAPI/v2/timeseries/data/
```

**Comment by jrmerz** [comment]
I found this tool: http://data.bls.gov/oes/, not sure if it will help.  The occupation id: 452091 wasn't listed... I tried another and the query was still fubar.  Though I have 0 idea what I am trying to get at.

**Comment by qjhart** [comment]
@blyeo @judyhanna  have developed an alternative labor cost method.
