### ISSUE TITLE
Send out list of potential list of labor types for Judy to review,   

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#12]

**Comment by ncparker** [comment]
Ag. job titles can be found at the link below. I think we need at least 45-2091 and 45-2092 (Equipment operators and laborers) and I've asked Judy to review other titles.
http://www.bls.gov/oes/current/oes_ca.htm#45-0000

Transport job titles can be found at the link below. We need data for 53-3032 (Heavy duty truck and trailer drivers).  Not sure if we want any others.
http://www.bls.gov/oes/current/oes_ca.htm#53-0000

**Comment by judyhanna** [comment]
45-2091 and 45-2092 should cover all the labor needs.
