### ISSUE TITLE
Develop a land costs / acre for the entire region.

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#14]
Nathan sez there is a cost for land-rent but it's only available by county and irrigated vs, non-irrigated.
Nathan used non-irrigated land rent.

**Comment by qjhart** [comment]
Nathan thinks that this is done annually.

**Comment by ncparker** [comment]
I've added land rent for irrigated cropland as a data dump from NASS for counties in CA/ID/OR/WA.

**Comment by qjhart** [comment]
@ncparker, Before I close this issue, I'm going to suggest some minor modifications to your input format, (basically less columns) ,but it looks good, thanks.

**Comment by blyeo** [comment]
Hi--How do I see the data that has been uploaded?

**Comment by qjhart** [comment]
It's hard to know this in advance, but Nathan could have automatically upated this issue by referencing #14 in comment when he committed, otherwise, here, I can reference the commit, 91ade2c6033fd84b59987d0bcf77b99ae92e99d8, and you can follow that to see the file(s) he added and modified.  You can either download the files individually or better yet, clone the repo on your site.

**Comment by ncparker** [comment]
Ok I'm slow at learning.. I've reduced the columns and added a 5 digit FIPS code.  The file can be found here: farm-budgets-data/data/costs/ucd/NASS land rent 2008-2014.csv

I'll reference the issue next time.  I've got the idea now.

**Comment by blyeo** [comment]
Hi-shall we set up a master excel sheet where we can enter all these data to the corresponding region and crops- SWAP format? Pls also delegate someone to enter the data in the correct format once we agree on the data we want to use for each of the cost categories.

**Comment by qjhart** [comment]
@ncparker I've been draconian in removing columns from this file, I hope that's okay with you.
