### ISSUE TITLE
How are $s represented in cost data.

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#17]
The standard units of measure  doesn't include dollar amounts.  I don't understand how we defined $ in our costs.  Should we say that if the cost includes a year, then the $ are for that year?  Should we say _every_ cost needs to have a year, and costs are always to that year? I like that the best.  Can we add a 'costs' section to the wiki however we do it?

**Comment by blyeo** [comment]
Hi--To be consistent, all costs should be in 2009 year and expressed as
$/acre for all the items we are tracking. For example, in each cell for
each crop and region it should be $ land rent/acre for 2009. The reason why
I say 2009 is because all of Santiago's budget are in 2009.
