### ISSUE TITLE
Add county to agricultural district crosswalk and incorporate into data pulling hierarchy 

### ISSUE THREAD

**Issue by ncparker** [CSTARS/farm-budgets-data#18]
Nathan will get national crosswalk.

**Comment by qjhart** [comment]
There is a county-Ag District crosswalk: https://github.com/CSTARS/farm-budgets-data/blob/master/data/nass/county_adc.csv
This comes from the NASS dataset. It's only for the AHB region currently.

**Comment by blyeo** [comment]
How do I download the Excel file from Github? Do I need to first install
Github on my computer before I can do that? Thanks!

**Comment by blyeo** [comment]
I'm not able to download the file from GitHub. Could you please advise what I'd need to do to be able to download/upload files from github?

Would you be able to give us the data for the other crops in non-irrigated lands-the corresponding acreage, yield, FIPS code, state, etc 

Thanks!
