### ISSUE TITLE
Getting Farm Budget Tool available online 

### ISSUE THREAD

**Issue by vbandaru9** [CSTARS/farm-budgets-data#19]
-Enhancing features of Farm Budget Tool
-Make it available online for showing to USDA team.
-Add some slides to https://docs.google.com/presentation/d/18bWQ89QOGTHedwkK0w-KSCBBvohpzXCUMM3o-gylRsc/edit#slide=id.p

**Comment by jrmerz** [comment]
@vbandaru9 can you be a little more specific with this?  Also, lets me this conversation to the repo: https://github.com/CSTARS/farm-budgets-app

**Comment by vbandaru9** [comment]
I just added this as a reminder. I dont have any specific request on this. I guess farm budget tool is running online and available for others to use. So just what ever things you guys think of to make it better, pls do it before executive meeting.

**Comment by jrmerz** [comment]
Ok, it's in the process of getting lots better, but the lots-better-version is not near completion and won't be for some time.  I am branding the current version as well as adding simple instructions.  I am also adding a warning that this is only an early prototype.  This 'branded' update to the current version should be ready soon.

**Comment by jrmerz** [comment]
Branded version with instructions and warning is up.  It's a splash screen, so you have to dismiss before you can use the app.  http://farm-budgets.bioenergy.casil.ucdavis.edu
