### ISSUE TITLE
Add NASS Yield Data to the Budgets

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#22]
Incorporate New nass-summary data from v0.2-alpha

**Comment by qjhart** [comment]
via @blyeo,  Please take note that I was not able to find "HAY, TAME, (EXCL ALFALFA & SMALL GRAIN)" in the yield data that Quinn sent out. So we've (Nathan and I) have taken "HAY, (EXCL ALFALFA)" yield values for GrassHay values in the mastersheet instead.

I have uploaded a new file on git hub: commodity_yield_bly. During our meeting today we talked about obtaining an average crop yield from year 2007 to 2012. Please take a look at the Excel file I have put together. We are still missing quite a number of yield data--it appears that there are some crops where data is unavailable for that particular crop type in a particular location across 2007-2012. Please advise on what we shall do to fill the missing data. Thanks.

**Comment by qjhart** [comment]
@blyeo, you didn't upload a new file yet. However, I id'd you on an issue CSTARS/nass-summary#2 where I will try and pull production data from the nass census data.  Also, note I moved this from the previous issue that was un-related.

**Comment by qjhart** [comment]
@blyeo / @ncparker / @hitchpy  I have uploaded a new yield file, commodity_county_harvest.  This provides yield estimates for each commodity and county.  The table is described in https://github.com/CSTARS/farm-budgets-data/wiki/nass

As you can see however, there still needs to have some additional processing if you need yields for both irrigated and non-irrigated commodities within a county.  Please let me know if that is a requirement.

**Comment by blyeo** [comment]
@qjhart @ncparker @hitchpy Thank you Quinn. In our previous discussion, we'd said that we'd use 
HAY, (EXCL ALFALFA) for grass hay, and HAYLAGE (EXCL ALFALFA) for grass  haylage. However, these two items are missing in the file "commodity_county_harvest" so we do not have any values for grass hay or grass haylage. Also, there is no data for potatoes.

**Comment by hitchpy** [comment]
@blyeo  Just uploaded what I gathered for harvest acreage at nass-summary/combined_harvest.csv
Indeed, those information are from survey data, indicated in the source_desc column

**Comment by blyeo** [comment]
@hitchpy The harvest acreage is different from what we are discussing in this github thread...I think @qjhart  had changed the file name from "commodity_county_harvest" to "commodity_county_yield", which is the file I am currently working on now to get the yield averages. Thank you.

**Comment by qjhart** [comment]
@blyeo / @hitchpy   
- There is still a commodity_harvest which includes production values, but not yields at each level
- There is a HAYLAGE, (EXCL ALFLAFA)  Note the comma
- There is a HAY, TAME, (EXCL ALFALFA) (Need to add TAME if that's what is appropriate)
- POTATOES, Hmm, there is no PRODUCTION in CENSUS data.  There should be statewide checks however.  I will review

**Comment by qjhart** [comment]
@blyeo  with 0fd7d9b created a swap ready csv file at: https://github.com/CSTARS/farm-budgets-data/blob/master/swap/swap_yield.csv or https://github.com/CSTARS/farm-budgets-data/blob/master/swap/swap.csv
