### ISSUE TITLE
Crop prices at the county level 

### ISSUE THREAD

**Issue by blyeo** [CSTARS/farm-budgets-data#27]
@qjhart @ncparker Please generate a file similar to the yield file but for crop prices. We discussed during the meeting today that we will also check the crop prices we have on file with the NASS data. I am presuming we will obtain an average price of 2007-2012 like we are doing for the yield data as well and not just look at 2009 prices?

**Comment by qjhart** [comment]
@blyeo, the current price table has all the data from 2005 on.  If you need to average that over all years, and/or gap fill, I think you have enough information already.  As I said however, price data seems to be pretty paltry in the NASS summary data I found.

**Comment by blyeo** [comment]
which Excel file should I be looking at to get the price data?

**Comment by qjhart** [comment]
@blyeo  nass/commodity_price
