### ISSUE TITLE
Poplar yield at the county level 

### ISSUE THREAD

**Issue by blyeo** [CSTARS/farm-budgets-data#28]
@qjhart @ncparker Quinn had sent the poplar yield by county last week and provided data with the following column headings:
1) fips
2) irrigated yield (what unit is this in?)
3) nonirrigated yield (what unit is this in?)
4) irrigation (cm/acre) 

I am comparing and contrasting it to the OLD poplar yield at the CMZ level we had and what we had to do with the data to get it into the form we need. 

In the previous/old poplar yield and irrigation table we had in the CMZ level, we have the following data supplied by Quinn: 
1) [first 2 years of poplar biomass] irrigated_2 years
2) irrigation_2yr (I am presuming these are the irrigation levels in cm/acre)?
3) nonirrigation_2yr (I am presuming these are the irrigation levels in cm/acre)?
4) [mature poplar biomss] irrigated 
5) [mature poplar biomass] irrigation (I am presuming these are irrigation levels in cm/acre)? 
6) [mature poplar biomass] nonirrigatiom (I am presuming these are nonirrigation levels in cm/acre)? 

We then used the "[first 2 years of poplar biomass] irrigated_2years" and "[mature poplar biomass] irrigated" variables to calculate "average annual yield (fresh ET/acre)".  The "average annual yield (fresh ET/acre)" is the poplar yield that we included in the BCAM model. Should this also be the yield level we provide SWAP? If so, then when calculating the cost per acre, why are we only including the mature_yield and not also the [first 2 years of poplar biomass]. In other words, why aren't we applying "average annual yield (Fresh ET/acre)" in the formula below to calculate the variable poplar cost per acre? 

Nathan says:
Cost per acre = $51.11/acre/year + ($15.28/BDT)*mature_yield
where mature_yield is the yield in dry tons (US or English) per acre (column R in the Poplar _yield... spreadsheet you sent earlier in this email chain)

I calculated the costs with labor separated from the Sustainability Metrics 1.0.xlsx.  The calculations are in the attached sheet. 

Non-machine labor: 2.53 hrs/acre/year
Machine labor: 0.93 hrs/acre/year + (0.378 hrs/BDT)_mature_yield
Other variable costs: $51.11/acre/year + ($15.28/BDT)_mature_yield

```
Prices, Ton /acre - This is a model parameter that is varied (AGREE)
Yield, Ton/acre - 3PG result from Quinn (AGREE--DONE)
Area (acres) - 0 or some small started value that is a calibration factor (AGREE)
cost of land rental ($/acre) - get it from the land cost of incumbent crops (***I need help here--see my e-mail to Quinn. But for now, I just went ahead and used state level land rent)
use of labor (hours/acre) - Calculate from info this morning (Non-machine labor: 2.53 hrs/acre/year and Machine labor: 0.93 hrs/acre/year + (0.378 hrs/BDT)*mature_yield) (DONE--See calculations in the Poplar Yield by State Excel sheet--already cut and pasted onto Mastersheet as well)
cost of labor ($/hour) - use the costs you developed for machine and non machine labor for other crop budgets (DONE)
applied water ( acre-ft per acre (ft)) - Did Steve answer this question (Yes--see below what he said and I've included these values in the Excel file)
all other variable costs ($/acre) - $51.11/acre/year + ($15.28/BDT)*mature_yield (See column AA in the poplar yield by state Excel file)
(DONE--See calculations in the Poplar Yield by State Excel sheet--already cut and pasted onto Mastersheet as well)
cost of water ($ per acre-ft) - use irrigation cost values Judy was working on (Same problem as land rental rate--but I went ahead and just used state level average irrigation cost)
```

***7. applied water ( acre-ft per acre (ft)) - Did Steve answer this question (Yes--here is what he said and I've included these values in the Excel file)

California--use almond trees as proxy for poplar trees

Washington--use apple trees as proxy for poplar trees

Idaho--use alfalfa hay irrigation levels

Montana--use alfalfa hay irrigation levels
Oregon--use alfalfa hay irrigation levels

**Comment by ncparker** [comment]
@blyeo with our previous poplar budget we input both the 2yr yield and the mature yield into the budget to find the cost.  When generalizing the results, I found that the 2yr yield was roughly a factor of 0.56 of the mature yield.  For ease of calculation I used this factor in creating the budget that is represented in the equations you referenced above.  

I don't know why Mark insisted on the fresh yield for BCAM it made no sense to me because then you have to always be worried about moisture content conversions.  In the end it doesn't really matter as long as you get all the conversions right.  My recollection is that 3PG results in dry metric tons per hectare.  I would guess the yields given are annualized but @qjhart would need to confirm.  This means I would need to adjust the cost equation to reflect the annualized yield instead of the mature yield (really the mature annual increment).

**Comment by blyeo** [comment]
@qjhart Please take a look at the worksheet "poplar yield" in the mastersheet120612thisistheone_BLY05162015_NP file. There are a few fips code where I am not able to match to Ag District, and State. I've filled in the land rental rate, irrigation costs, labor hours, and labor costs for the poplar yield you gave. Thank you.

**Comment by blyeo** [comment]
@qjhart Could you please let us know what is the unit for all the poplar yield data you provided us last week? 1) fips
2) irrigated yield (what unit is this in?)
3) nonirrigated yield (what unit is this in?)
4) irrigation (cm/acre) 

@ncparker asks: are the yields Quinn gave mature or avg annual yield and what units they are in? Does it take into account the [first 2 years of poplar biomass] irrigated_2 years?

**Comment by qjhart** [comment]
@blyeo / @ncparker the wiki page, https://github.com/CSTARS/farm-budgets-data/wiki/ucd_ahb describes the yield table.  Quickly, yields in dry basis Mg/ha/yr and irrigation in cm/ha/yr.  Also, the current table has the average of all harvests in there.  I forgot about the previous table, and I can pull out the first coppice easily if that is desired.

**Comment by blyeo** [comment]
@qjhart Please take a look at the worksheet "poplar yield" in the mastersheet120612thisistheone_BLY05162015_NP file. There are a few fips code where I am not able to match to Ag District, and State so it appears as "#N/A". I've filled in the land rental rate, irrigation costs, labor hours, and labor costs for the poplar yield you gave. Thank you.

**Comment by blyeo** [comment]
@ncparker @qjhart I have already updated the "poplaryield" worksheet. I used the "irrigated_yield (dry basis Mg/ha/yr)" and divide it by 2.24 to get "irrigated_yield (BDT/acre)". I then applied the formula: "$51.11/acre/year + ($15.28/BDT)*mature_yield" to get the poplar variable cost per acre. This completes all the data we need for the poplar yield and production cost. However, there are still a number of fips code where we are missing land rent, irrigation rates, etc. as I am not able to match the fips to a particular ag district and state. @qjhart please take a look. 

@ncparker noted your comments on having 2 different irrigation levels for poplar: (1) based on irrigation levels that Quinn gave us. I changed cm/ha/year to acre-feet/acre-year in column J. I have also (2) included proxies of irrigation levels based on almond trees irrigation needs in California, apple tress in Washington, and alfalfa hay in Idaho, Montana, and Oregon (for these 3 states they are 2 acre-ft/acre/year).
