### ISSUE TITLE
poplar irrigation levels by county (ft/acre)

### ISSUE THREAD

**Issue by blyeo** [CSTARS/farm-budgets-data#29]
@qjhart @ncparker  

Is the 4th column in the "poplar_yield.csv" file that Quinn provide "irrigation (cm/acre)", irrigation levels for poplar? If so, then why aren't we using this irrigation for poplar irrigation levels but instead we are using the following irrigation estimations for poplar instead? Thanks for clarifying.  

California--use almond trees as proxy for poplar trees

Washington--use apple trees as proxy for poplar trees

Idaho--use alfalfa hay irrigation levels

Montana--use alfalfa hay irrigation levels
Oregon--use alfalfa hay irrigation levels

**Comment by ncparker** [comment]
not sure why I'm assigned to this... @blyeo the 3PG model calculates the water needed beyond rainfall in order for poplar to produce the predicted yield. From this @qjhart has estimated irrigation required including loss factors, I believe.  That is the value in the poplar_yield file.  This estimate has been declared too low by Steve (possibly supported by the Clarksburg irrigation schedule)  I don't know if there is any empirical evidence that these modeled values are too low.  We have decided to use the proxies mentioned above as an alternative method.  I think we are still interested in both scenarios.

**Comment by blyeo** [comment]
Okay--noted. I will have two columns for irrigation levels for poplar: (1) proxies mentioned above; (2) irrigation levels provided by @qjhart.

**Comment by qjhart** [comment]
@blyeo / @ncparker Yes, that is correct.  The estimates were considered too low for Steve, but I have not seen any  corroborating evidence to that effect.
