### ISSUE TITLE
Commodity_price data 

### ISSUE THREAD

**Issue by blyeo** [CSTARS/farm-budgets-data#30]
@qjhart @ncparker I wanted to calculated average commodity prices from year 2007-2012 like we did for commodity yield. I opened the file "commodity_price" but it does not have prices for the commodities we need. @qjhart would you be able to generate another "commodity price" file that consists of the crops we need?  

Here is a list of commodities in the "commodity price" file:
artichokes
asparagus
asparagus, fresh market
asparagus, processing
beans
beans, snap
beans, snap, fresh market
beans, snap, processing
broccoli
broccoli, fresh market
broccoli, processing
cabbage
cabbage, fresh market
carrots
carrots, fresh market
carrots, processing
cattle
cattle, (excl calves)
cattle, calves
cauliflower
cauliflower, fresh market
cauliflower, processing
celery
cucumbers
cucumbers, fresh market
garlic
hogs
lettuce
lettuce, head
lettuce, head, fresh market
lettuce, leaf
lettuce, leaf, fresh market
lettuce, romaine
lettuce, romaine, fresh market
melons
melons, cantaloup
melons, cantaloup, fresh market
melons, honeydew
melons, honeydew, fresh market
melons, watermelon
melons, watermelon, fresh market
mohair
mohair, angora
onions
onions, dry
onions, dry, spring
onions, dry, summer
onions, dry, summer, non-storage
onions, dry, summer, storage
peas
peas, green
peas, green, processing
peppers
peppers, bell
peppers, chile
pumpkins
sheep
sheep, (excl lambs)
sheep, lambs
spinach
spinach, fresh market
spinach, processing
squash
strawberries
strawberries, fresh market
strawberries, processing
sweet corn
sweet corn, fresh market
sweet corn, processing
tomatoes
tomatoes, fresh market
tomatoes, processing
turkeys
wool
(blank)

However, we need prices from year 2007-2012 for the following commodities: 
alfalfa hay
alfalfa haylage
barley
beans,dry edible
beans, dry lima
canola
corn grain
corn silage
grass hay
grass haylage
lentils
oats
potatoes
spring wheat
sugarbeets
winter wheat

**Comment by qjhart** [comment]
Fixed with 3e7a731.  @blyeo / @ncparker  Because almost all of the issues that I'm tracking are now related explicitly to the SWAP runs and not the farm_budget_data online, I will start to limit the data to the commodities that are identified above.  In this case, I have updated the nass/commodity_price.csv file and the nass/commodity_avg_price.csv file.  This is all survey data, and only available at the state level.
I've included all the commodity breakouts from the above list of commodities.

**Comment by blyeo** [comment]
Hi Quinn,
I don't see these files in my github folder. Did you already commit these
files? Could you please try reloading on github?
Thanks,
Boon Ling

**Comment by blyeo** [comment]
https://github.com/CSTARS/farm-budgets-data/tree/master/nass

I see it on the website but not in my github folder on my computer...

**Comment by qjhart** [comment]
Did you sync? (Upper right corner of your tool?)

**Comment by blyeo** [comment]
I am having some trouble syncing... As I have worked on some excel files on
the github folder and github can't sync unless I commit all changes...

You'd mentioned I can't sync non csv files right? So I should remove the
regular excel files? It seems to be giving me problems...

**Comment by qjhart** [comment]
You can sync XLS files, I said you an't track changes on them, but you can upload new ones.

**Comment by blyeo** [comment]
Github says I have 38 files I have to commit, but I don't...

**Comment by qjhart** [comment]
I think by default any files in the directory are included, you should be able to unselect them.

**Comment by blyeo** [comment]
I used the latest commodity_avg_price.cvs file that @qjhart posted yesterday. Here is a list of crops that's still missing:
alfalfa haylage 
beans, dry lima
corn grain 
corn silage
grass haylage

**Comment by blyeo** [comment]
@ncparker @qjhart I have already inserted the "commodity_average_price" into the "mastersheet_clean" worksheet. The good news is that the price for almost all the "commodity_average_price" that we have is higher than the old prices we had from Mark. This should help with the negative profits problem we have been having. I inserted a separate column "AI" in the "mastersheet_clean" to check the difference between "commodity average price" that Quinn posted with the prices that Mark had previously. It shows that all the values are positive except for sugarbeets. 

Furthermore, we have a number of missing crops from the "commodity_avg_price" data that so there prices for the following crops below shows N/A: 

alfalfa haylage
beans, dry lima
corn grain
corn silage
grass haylage

**Comment by qjhart** [comment]
@blyeo From the NASS data, the only price for alfalfa is the 
- For alfalfa 'HAY, ALFALFA' as reported.
- Beans only 'BEANS, DRY EDIBLE'
- there are no prices for any haylage
- Corn is strange, There are prices in there, but they are not broken down by class (Grain vs Silage), but there is a 'UTIL_PRACTICE' description that sez grain, so I am going to assume this is the grain price only, and I can add that in.

**Comment by qjhart** [comment]
@blyeo Updated for CORN, GRAIN prices.

**Comment by qjhart** [comment]
@blyeo FYI, Lima beans are in the DRY, EDIBLE category, so I would use that I suppose for those prices.  I don't know what to do about haylage and silage

**Comment by ncparker** [comment]
@blyeo Check the 'Haylage2Hay' and 'SilagePriceWksht' sheets in the Mastersheet.... excel file.  There are no reported value for silage and haylage prices but they can be given prices based on corn and hay prices.  The corn silage is valued roughly for its grain content.  Mark created a nice way to estimate the state average price using yields of silage and grain within a state and the corn grain price.  For the haylage crops, based on equivalent dry matter value haylage is worth roughly 1/3 of of the value of hay.  So for alfalfa haylage take the alfalfa hay price and divide by 3 to get the alfalfa haylage price.

**Comment by qjhart** [comment]
Josue says we are mistaken and there is price data available at the county level for both haylage and silage.  This is located at: http://www.nass.usda.gov/Statistics_by_State/California/Publications/AgComm/Detail/index.asp

However, this is for California only.  So from this data, we could estimate prices by comparing the haylage and silage date from the CA Ag commissioners report, and use the same conversion factors that are included in the California data.
