### ISSUE TITLE
'make import' fails on fresh install

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/farm-budgets-data#31]
Running make import fails due to missing farm_budget_data on fresh install. Message:

LINE 23: update farm_budget_data.production set commodity=x.nass from...
                ^
for c in ; do\
     psql -d nass --variable=cwd=/Users/jrmerz/dev/cstars/farm-budgets-data/ -c "\COPY farm_budget_data.production (authority,material,location,phase,commodity,unit,amount) from $c with csv header";\
     f=`basename $c .csv | sed -e 's/^...//'`;\
    psql -d nass --variable=cwd=/Users/jrmerz/dev/cstars/farm-budgets-data/ -c "update farm_budget_data.production set commodity=upper(trim( both from replace('$f','_',' '))) where commodity is null";\
    done;
psql -d nass --variable=cwd=/Users/jrmerz/dev/cstars/farm-budgets-data/ -c "select farm_budget_data.fix_production();";
ERROR:  schema "farm_budget_data" does not exist
make: **\* [import] Error 1

**Comment by qjhart** [comment]
@jrmerz, I have modified the Makefile however, to use services rather than a direct call.  The default service is farm-budgets-data, so my .pg_service.conf file includes the items below.  To test the setup in another db, you can do as `make PG.service=quinn import`

```
[farm-budgets-data]
port=5432
user=quinn
dbname=nass

[quinn]
port=5432
user=quinn
dbname=quinn
```
