### ISSUE TITLE
Review the Phase / Operations section for the budgets

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#32]
I have identified about 75 line items in the current budgets that are not materials, but instead are operations.  Things like 'Baling....'.  These are contained in the operations.csv file.  I have pulled them out of the materials section, and I've added a phase to them.   There are currently only three phases.

``` sql
CREATE TYPE phase_t AS ENUM ('planting', 'annual', 'harvest');
```

The idea I have is that users can select different operations inside each phase, and then budget for each operation.  That way, they can think in more detail about each part of the farm operation, as they do their budgets.  The production table then includes an operation (and phase?) for each material.  This allows the use to look at parts of the budget at a time.  

In terms of the application, then.  The user would see a complete budget, but then be able to see costs of each phase, and inside that, the cost of each operation.   Inside each operation, they'd see the price for each material.

**Comment by qjhart** [comment]
You can see a more detailed description, with time frames at: https://docs.google.com/drawings/d/1vloNI7Ztfw10uvW3pcJi6pd7Cz0Ej8njCdUXIFMNb_g/edit?usp=sharing

**Comment by jrmerz** [comment]
@qjhart just to verify, the production table has a phase, but does not yet have a operation?

**Comment by jrmerz** [comment]
@qjhart do you still want to have a 'phase' attribute implemented?  Looks like it would really be 'operation groups'?
