### ISSUE TITLE
Too many production values of 1? 

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#33]
Inside the production table, we have materials and/or operations that are specified with a value of 1.  To me this doesn't make sense.  

``` sql
select distinct material,unit from production where amount=1 order by 1,2;
```

To me lots of these look like simple dollar estimates, which is fine, but then the production table should be showing these.  For example, Let's say material,`Lube`, if you are estimating a cost of Lube, then the material table should probably have a unit '$' and the production should have your estimate like 340.

I'm curious where those estimates went in the retrieval of the original budgets

**Comment by jrmerz** [comment]
Using 'Lube' as an example, I think that is supposed to be price (located in price table) for every one 1 acre.  Currently the price is 4.35, so $4.35 per acre of use.  You can see original data here: https://docs.google.com/spreadsheets/d/1ELVT6IBOiVHtC9SCE2GzVFgAILwAsulNCVUR6jXp2II/edit#gid=461475061 (line 39)

**Comment by ncparker** [comment]
Some things in the original Cost/Return Studies from which the budgets are developed just have a value per acre.  Taking the 'Lube' example, the rice cost/return study has a value of $21/per acre but no quantity/acre, unit or cost/unit value given.  See Table 2 (page 13) in this report:
http://coststudyfiles.ucdavis.edu/uploads/cs_public/c5/11/c511c794-1e63-42f7-91c6-ce1b4c6b5917/rice-sv-2015.pdf

I haven't done a comparison of the Santiago budgets spreadsheet with the cost/return studies to see if there are things he simplified that are reported in the studies.
