### ISSUE TITLE
Rethink our entire farm-budgets-data

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#36]
One idea for the farm-budgets-data repo, was that we could create a set of CSV files that would serve equally well as input into our budgeting data, as well as input into a spreadsheet.  The idea being you could make changes in the spreadsheet quicker than in the application, and get some benefit from that.  However, we have found in general that:
- It's pretty easy to do most things in the application
- We don't have a good export from the application, so this strategy is pretty lacking in terms of utility in interchange of tools.
- Lot's of the wholesale changes we are thinking are more easily programmed in JS and not spreadsheets anyways.

So, we are thinking it's maybe best to ditch this method, and just save directly the JSON representation of farms, materials, and prices.

@jrmerz and I have discussed some different plans for this, some involving a continuously running mongodb, in which case this would be just a periodic dump of that db at various stages.

**Comment by jrmerz** [comment]
Using command line JS and JSON 'export'.
