### ISSUE TITLE
Verify that Santiago's Budget is all incorporated into the farm budget data.

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#7]

**Comment by qjhart** [comment]
If adding new budgets from Santiagos' sheets is a admin cut and paste, and is done manually, can we add a quick item on how to do that to the editor page ?

**Comment by jrmerz** [comment]
@qjhart I will make a quick screen cast, it's a very 'hacky' process.

**Comment by jrmerz** [comment]
All of Santiago's budgets have been added here 6dd6d77.  There are two notes.
- The Alfalfa Seed sheet as not state associated with it
- The costs are shared across state for all crops and can sometimes very greatly from crop to crop in the budget.  The importer just overwrites the last amount, so many of the values do not reflect what is in the spreadsheet.

**Comment by jrmerz** [comment]
The screencast is now online [here](https://drive.google.com/open?id=0B_7cUV-o2QQYWUpCVlgzRW1CWUU&authuser=0).  Please email me with your gmail account if you want access to the admin interface.  I would like to reiterate, this is an early prototype.  So step lightly.
